name: Build and Test

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    uses: garemat/moonstone-companion/.github/workflows/validate.yml@main
    with:
      pr_body: ${{ github.event.pull_request.body }}
